using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SZTF1_ZH2_A
{
    public static class ZHHelper
    {
        public static Epizod[] GenerateData()
        {
            return new Epizod[]
            {
                new Epizod(){Sorszam=1,Evad=1,EvadResz=1, Cim="Pilot",Rendezo="David Nutter",Premier="October 10, 2012",NezoSzam=4.14},
                new Epizod(){Sorszam=2,Evad=1,EvadResz=2, Cim="Honor Thy Father",Rendezo="David Barrett",Premier="October 17, 2012",NezoSzam=3.55},
                new Epizod(){Sorszam=3,Evad=1,EvadResz=3, Cim="Lone Gunmen",Rendezo="Guy Bee",Premier="October 24, 2012",NezoSzam=3.51},
                new Epizod(){Sorszam=4,Evad=1,EvadResz=4, Cim="An Innocent Man",Rendezo="Vince Misiano",Premier="October 31, 2012",NezoSzam=3.05},
                new Epizod(){Sorszam=5,Evad=1,EvadResz=5, Cim="Damaged",Rendezo="Michael Schultz",Premier="November 7, 2012",NezoSzam=3.75},
                new Epizod(){Sorszam=6,Evad=1,EvadResz=6, Cim="Legacies",Rendezo="John Behring",Premier="November 14, 2012",NezoSzam=3.83},
                new Epizod(){Sorszam=7,Evad=1,EvadResz=7, Cim="Muse of Fire",Rendezo="David Grossman",Premier="November 28, 2012",NezoSzam=3.74},
                new Epizod(){Sorszam=8,Evad=1,EvadResz=8, Cim="Vendetta",Rendezo="Ken Fink",Premier="December 5, 2012",NezoSzam=3.35},
                new Epizod(){Sorszam=9,Evad=1,EvadResz=9, Cim="Year's End",Rendezo="John Dahl",Premier="December 12, 2012",NezoSzam=3.11},
                new Epizod(){Sorszam=10,Evad=1,EvadResz=10, Cim="Burned",Rendezo="Eagle Egilsson",Premier="January 16, 2013",NezoSzam=3.06},
                new Epizod(){Sorszam=11,Evad=1,EvadResz=11, Cim="Trust But Verify",Rendezo="Nick Copus",Premier="January 23, 2013",NezoSzam=3.14},
                new Epizod(){Sorszam=12,Evad=1,EvadResz=12, Cim="Vertigo",Rendezo="Wendey Stanzler",Premier="January 30, 2013",NezoSzam=2.97},
                new Epizod(){Sorszam=13,Evad=1,EvadResz=13, Cim="Betrayal",Rendezo="Guy Bee",Premier="February 6, 2013",NezoSzam=2.96},
                new Epizod(){Sorszam=14,Evad=1,EvadResz=14, Cim="The Odyssey",Rendezo="John Behring",Premier="February 13, 2013",NezoSzam=3.29},
                new Epizod(){Sorszam=15,Evad=1,EvadResz=15, Cim="Dodger",Rendezo="Eagle Egilsson",Premier="February 20, 2013",NezoSzam=3.15},
                new Epizod(){Sorszam=16,Evad=1,EvadResz=16, Cim="Dead to Rights",Rendezo="Glen Winter",Premier="February 27, 2013",NezoSzam=3.17},
                new Epizod(){Sorszam=17,Evad=1,EvadResz=17, Cim="The Huntress Returns",Rendezo="Guy Bee",Premier="March 20, 2013",NezoSzam=3.02},
                new Epizod(){Sorszam=18,Evad=1,EvadResz=18, Cim="Salvation",Rendezo="Nick Copus",Premier="March 27, 2013",NezoSzam=2.65},
                new Epizod(){Sorszam=19,Evad=1,EvadResz=19, Cim="Unfinished Business",Rendezo="Michael Offer",Premier="April 3, 2013",NezoSzam=2.92},
                new Epizod(){Sorszam=20,Evad=1,EvadResz=20, Cim="Home Invasion",Rendezo="Ken Fink",Premier="April 24, 2013",NezoSzam=3.10},
                new Epizod(){Sorszam=21,Evad=1,EvadResz=21, Cim="The Undertaking",Rendezo="Michael Schultz",Premier="May 1, 2013",NezoSzam=2.89},
                new Epizod(){Sorszam=22,Evad=1,EvadResz=22, Cim="Darkness on the Edge of Town",Rendezo="John Behring",Premier="May 8, 2013",NezoSzam=2.62},
                new Epizod(){Sorszam=23,Evad=1,EvadResz=23, Cim="Sacrifice",Rendezo="David Barrett",Premier="May 15, 2013",NezoSzam=2.77},
                new Epizod(){Sorszam=24,Evad=2,EvadResz=1, Cim="City of Heroes",Rendezo="John Behring",Premier="October 9, 2013",NezoSzam=2.74},
                new Epizod(){Sorszam=25,Evad=2,EvadResz=2, Cim="Identity",Rendezo="Nick Copus",Premier="October 16, 2013",NezoSzam=3.06},
                new Epizod(){Sorszam=26,Evad=2,EvadResz=3, Cim="Broken Dolls",Rendezo="Glen Winter",Premier="October 23, 2013",NezoSzam=2.89},
                new Epizod(){Sorszam=27,Evad=2,EvadResz=4, Cim="Crucible",Rendezo="Eagle Egilsson",Premier="October 30, 2013",NezoSzam=2.37},
                new Epizod(){Sorszam=28,Evad=2,EvadResz=5, Cim="League of Assassins",Rendezo="Wendey Stanzler",Premier="November 6, 2013",NezoSzam=2.80},
                new Epizod(){Sorszam=29,Evad=2,EvadResz=6, Cim="Keep Your Enemies Closer",Rendezo="Guy Bee",Premier="November 13, 2013",NezoSzam=3.09},
                new Epizod(){Sorszam=30,Evad=2,EvadResz=7, Cim="State v. Queen",Rendezo="Bethany Rooney",Premier="November 20, 2013",NezoSzam=2.66},
                new Epizod(){Sorszam=31,Evad=2,EvadResz=8, Cim="The Scientist",Rendezo="Michael Schultz",Premier="December 4, 2013",NezoSzam=3.24},
                new Epizod(){Sorszam=32,Evad=2,EvadResz=9, Cim="Three Ghosts",Rendezo="John Behring",Premier="December 11, 2013",NezoSzam=3.02},
                new Epizod(){Sorszam=33,Evad=2,EvadResz=10, Cim="Blast Radius",Rendezo="Rob Hardy",Premier="January 15, 2014",NezoSzam=2.52},
                new Epizod(){Sorszam=34,Evad=2,EvadResz=11, Cim="Blind Spot",Rendezo="Glen Winter",Premier="January 22, 2014",NezoSzam=2.49},
                new Epizod(){Sorszam=35,Evad=2,EvadResz=12, Cim="Tremors",Rendezo="Guy Bee",Premier="January 29, 2014",NezoSzam=2.95},
                new Epizod(){Sorszam=36,Evad=2,EvadResz=13, Cim="Heir to the Demon",Rendezo="Wendey Stanzler",Premier="February 5, 2014",NezoSzam=2.86},
                new Epizod(){Sorszam=37,Evad=2,EvadResz=14, Cim="Time of Death",Rendezo="Nick Copus",Premier="February 26, 2014",NezoSzam=2.45},
                new Epizod(){Sorszam=38,Evad=2,EvadResz=15, Cim="The Promise",Rendezo="Glen Winter",Premier="March 5, 2014",NezoSzam=2.21},
                new Epizod(){Sorszam=39,Evad=2,EvadResz=16, Cim="Suicide Squad",Rendezo="Larry Teng",Premier="March 19, 2014",NezoSzam=2.42},
                new Epizod(){Sorszam=40,Evad=2,EvadResz=17, Cim="Birds of Prey",Rendezo="John Behring",Premier="March 26, 2014",NezoSzam=2.62},
                new Epizod(){Sorszam=41,Evad=2,EvadResz=18, Cim="Deathstroke",Rendezo="Guy Bee",Premier="April 2, 2014",NezoSzam=2.32},
                new Epizod(){Sorszam=42,Evad=2,EvadResz=19, Cim="The Man Under the Hood",Rendezo="Jesse Warn",Premier="April 16, 2014",NezoSzam=2.26},
                new Epizod(){Sorszam=43,Evad=2,EvadResz=20, Cim="Seeing Red",Rendezo="Doug Aarniokoski",Premier="April 23, 2014",NezoSzam=2.19},
                new Epizod(){Sorszam=44,Evad=2,EvadResz=21, Cim="City of Blood",Rendezo="Michael Schultz",Premier="April 30, 2014",NezoSzam=2.31},
                new Epizod(){Sorszam=45,Evad=2,EvadResz=22, Cim="Streets of Fire",Rendezo="Nick Copus",Premier="May 7, 2014",NezoSzam=2.33},
                new Epizod(){Sorszam=46,Evad=2,EvadResz=23, Cim="Unthinkable",Rendezo="John Behring",Premier="May 14, 2014",NezoSzam=2.37},
                new Epizod(){Sorszam=47,Evad=3,EvadResz=1, Cim="The Calm",Rendezo="Glen Winter",Premier="October 8, 2014",NezoSzam=2.83},
                new Epizod(){Sorszam=48,Evad=3,EvadResz=2, Cim="Sara",Rendezo="Wendey Stanzler",Premier="October 15, 2014",NezoSzam=2.32},
                new Epizod(){Sorszam=49,Evad=3,EvadResz=3, Cim="Corto Maltese",Rendezo="Stephen Surjik",Premier="October 22, 2014",NezoSzam=2.55},
                new Epizod(){Sorszam=50,Evad=3,EvadResz=4, Cim="The Magician",Rendezo="John Behring",Premier="October 29, 2014",NezoSzam=2.49},
                new Epizod(){Sorszam=51,Evad=3,EvadResz=5, Cim="The Secret Origin of Felicity Smoak",Rendezo="Michael Schultz",Premier="November 5, 2014",NezoSzam=2.73},
                new Epizod(){Sorszam=52,Evad=3,EvadResz=6, Cim="Guilty",Rendezo="Peter Leto",Premier="November 12, 2014",NezoSzam=2.60},
                new Epizod(){Sorszam=53,Evad=3,EvadResz=7, Cim="Draw Back Your Bow",Rendezo="Rob Hardy",Premier="November 19, 2014",NezoSzam=2.64},
                new Epizod(){Sorszam=54,Evad=3,EvadResz=8, Cim="The Brave and the Bold",Rendezo="Jesse Warn",Premier="December 3, 2014",NezoSzam=3.92},
                new Epizod(){Sorszam=55,Evad=3,EvadResz=9, Cim="The Climb",Rendezo="Thor Freudenthal",Premier="December 10, 2014",NezoSzam=3.06},
                new Epizod(){Sorszam=56,Evad=3,EvadResz=10, Cim="Left Behind",Rendezo="Glen Winter",Premier="January 21, 2015",NezoSzam=3.06},
                new Epizod(){Sorszam=57,Evad=3,EvadResz=11, Cim="Midnight City",Rendezo="Nick Copus",Premier="January 28, 2015",NezoSzam=2.91},
                new Epizod(){Sorszam=58,Evad=3,EvadResz=12, Cim="Uprising",Rendezo="Jesse Warn",Premier="February 4, 2015",NezoSzam=2.94},
                new Epizod(){Sorszam=59,Evad=3,EvadResz=13, Cim="Canaries",Rendezo="Michael Schultz",Premier="February 11, 2015",NezoSzam=2.67},
                new Epizod(){Sorszam=60,Evad=3,EvadResz=14, Cim="The Return",Rendezo="Dermott Downs",Premier="February 18, 2015",NezoSzam=2.91},
                new Epizod(){Sorszam=61,Evad=3,EvadResz=15, Cim="Nanda Parbat",Rendezo="Gregory Smith",Premier="February 25, 2015",NezoSzam=3.07},
                new Epizod(){Sorszam=62,Evad=3,EvadResz=16, Cim="The Offer",Rendezo="Dermott Downs",Premier="March 18, 2015",NezoSzam=2.56},
                new Epizod(){Sorszam=63,Evad=3,EvadResz=17, Cim="Suicidal Tendencies",Rendezo="Jesse Warn",Premier="March 25, 2015",NezoSzam=2.86},
                new Epizod(){Sorszam=64,Evad=3,EvadResz=18, Cim="Public Enemy",Rendezo="Dwight Little",Premier="April 1, 2015",NezoSzam=2.48},
                new Epizod(){Sorszam=65,Evad=3,EvadResz=19, Cim="Broken Arrow",Rendezo="Doug Aarniokoski",Premier="April 15, 2015",NezoSzam=2.47},
                new Epizod(){Sorszam=66,Evad=3,EvadResz=20, Cim="The Fallen",Rendezo="Antonio Negret",Premier="April 22, 2015",NezoSzam=2.72},
                new Epizod(){Sorszam=67,Evad=3,EvadResz=21, Cim="Al Sah-him",Rendezo="Thor Freudenthal",Premier="April 29, 2015",NezoSzam=2.39},
                new Epizod(){Sorszam=68,Evad=3,EvadResz=22, Cim="This Is Your Sword",Rendezo="Wendey Stanzler",Premier="May 6, 2015",NezoSzam=2.54},
                new Epizod(){Sorszam=69,Evad=3,EvadResz=23, Cim="My Name Is Oliver Queen",Rendezo="John Behring",Premier="May 13, 2015",NezoSzam=2.83},
                new Epizod(){Sorszam=70,Evad=4,EvadResz=1, Cim="Green Arrow",Rendezo="Thor Freudenthal",Premier="October 7, 2015",NezoSzam=2.67},
                new Epizod(){Sorszam=71,Evad=4,EvadResz=2, Cim="The Candidate",Rendezo="John Behring",Premier="October 14, 2015",NezoSzam=2.50},
                new Epizod(){Sorszam=72,Evad=4,EvadResz=3, Cim="Restoration",Rendezo="Wendey Stanzler",Premier="October 21, 2015",NezoSzam=2.40},
                new Epizod(){Sorszam=73,Evad=4,EvadResz=4, Cim="Beyond Redemption",Rendezo="Lexi Alexander",Premier="October 28, 2015",NezoSzam=2.64},
                new Epizod(){Sorszam=74,Evad=4,EvadResz=5, Cim="Haunted",Rendezo="John Badham",Premier="November 4, 2015",NezoSzam=2.60},
                new Epizod(){Sorszam=75,Evad=4,EvadResz=6, Cim="Lost Souls",Rendezo="Antonio Negret",Premier="November 11, 2015",NezoSzam=2.30},
                new Epizod(){Sorszam=76,Evad=4,EvadResz=7, Cim="Brotherhood",Rendezo="James Bamford",Premier="November 18, 2015",NezoSzam=2.69},
                new Epizod(){Sorszam=77,Evad=4,EvadResz=8, Cim="Legends of Yesterday",Rendezo="Thor Freudenthal",Premier="December 2, 2015",NezoSzam=3.66},
                new Epizod(){Sorszam=78,Evad=4,EvadResz=9, Cim="Dark Waters",Rendezo="John Behring",Premier="December 9, 2015",NezoSzam=2.82},
                new Epizod(){Sorszam=79,Evad=4,EvadResz=10, Cim="Blood Debts",Rendezo="Jesse Warn",Premier="January 20, 2016",NezoSzam=2.83},
                new Epizod(){Sorszam=80,Evad=4,EvadResz=11, Cim="A.W.O.L.",Rendezo="Charlotte Brandström",Premier="January 27, 2016",NezoSzam=2.78},
                new Epizod(){Sorszam=81,Evad=4,EvadResz=12, Cim="Unchained",Rendezo="Kevin Fair",Premier="February 3, 2016",NezoSzam=2.48},
                new Epizod(){Sorszam=82,Evad=4,EvadResz=13, Cim="Sins of the Father",Rendezo="Gordon Verheul",Premier="February 10, 2016",NezoSzam=2.44},
                new Epizod(){Sorszam=83,Evad=4,EvadResz=14, Cim="Code of Silence",Rendezo="James Bamford",Premier="February 17, 2016",NezoSzam=2.44},
                new Epizod(){Sorszam=84,Evad=4,EvadResz=15, Cim="Taken",Rendezo="Gregory Smith",Premier="February 24, 2016",NezoSzam=2.70},
                new Epizod(){Sorszam=85,Evad=4,EvadResz=16, Cim="Broken Hearts",Rendezo="John Showalter",Premier="March 23, 2016",NezoSzam=2.09},
                new Epizod(){Sorszam=86,Evad=4,EvadResz=17, Cim="Beacon of Hope",Rendezo="Michael Schultz",Premier="March 30, 2016",NezoSzam=2.34},
                new Epizod(){Sorszam=87,Evad=4,EvadResz=18, Cim="Eleven-Fifty-Nine",Rendezo="Rob Hardy",Premier="April 6, 2016",NezoSzam=2.24},
                new Epizod(){Sorszam=88,Evad=4,EvadResz=19, Cim="Canary Cry",Rendezo="Laura Belsey",Premier="April 27, 2016",NezoSzam=2.27},
                new Epizod(){Sorszam=89,Evad=4,EvadResz=20, Cim="Genesis",Rendezo="Gregory Smith",Premier="May 4, 2016",NezoSzam=2.07},
                new Epizod(){Sorszam=90,Evad=4,EvadResz=21, Cim="Monument Point",Rendezo="Kevin Tancharoen",Premier="May 11, 2016",NezoSzam=2.16},
                new Epizod(){Sorszam=91,Evad=4,EvadResz=22, Cim="Lost in the Flood",Rendezo="Glen Winter",Premier="May 18, 2016",NezoSzam=1.94},
                new Epizod(){Sorszam=92,Evad=4,EvadResz=23, Cim="Schism",Rendezo="John Behring",Premier="May 25, 2016",NezoSzam=2.19},
                new Epizod(){Sorszam=93,Evad=5,EvadResz=1, Cim="Legacy",Rendezo="James Bamford",Premier="October 5, 2016",NezoSzam=1.87},
                new Epizod(){Sorszam=94,Evad=5,EvadResz=2, Cim="The Recruits",Rendezo="James Bamford",Premier="October 12, 2016",NezoSzam=1.94},
                new Epizod(){Sorszam=95,Evad=5,EvadResz=3, Cim="A Matter of Trust",Rendezo="Gregory Smith",Premier="October 19, 2016",NezoSzam=1.79},
                new Epizod(){Sorszam=96,Evad=5,EvadResz=4, Cim="Penance",Rendezo="Dermott Downs",Premier="October 26, 2016",NezoSzam=1.87},
                new Epizod(){Sorszam=97,Evad=5,EvadResz=5, Cim="Human Target",Rendezo="Laura Belsey",Premier="November 2, 2016",NezoSzam=1.61},
                new Epizod(){Sorszam=98,Evad=5,EvadResz=6, Cim="So It Begins",Rendezo="John Behring",Premier="November 9, 2016",NezoSzam=1.95},
                new Epizod(){Sorszam=99,Evad=5,EvadResz=7, Cim="Vigilante",Rendezo="Gordon Verheul",Premier="November 16, 2016",NezoSzam=1.86},
                new Epizod(){Sorszam=100,Evad=5,EvadResz=8, Cim="Invasion!",Rendezo="James Bamford",Premier="November 30, 2016",NezoSzam=3.55},
                new Epizod(){Sorszam=101,Evad=5,EvadResz=9, Cim="What We Leave Behind",Rendezo="Antonio Negret",Premier="December 7, 2016",NezoSzam=1.94},
                new Epizod(){Sorszam=102,Evad=5,EvadResz=10, Cim="Who Are You?",Rendezo="Gregory Smith",Premier="January 25, 2017",NezoSzam=1.68},
                new Epizod(){Sorszam=103,Evad=5,EvadResz=11, Cim="Second Chances",Rendezo="Mark Bunting",Premier="February 1, 2017",NezoSzam=1.91},
                new Epizod(){Sorszam=104,Evad=5,EvadResz=12, Cim="Bratva",Rendezo="Ben Bray",Premier="February 8, 2017",NezoSzam=1.61},
                new Epizod(){Sorszam=105,Evad=5,EvadResz=13, Cim="Spectre of the Gun",Rendezo="Kristin Windell",Premier="February 15, 2017",NezoSzam=1.66},
                new Epizod(){Sorszam=106,Evad=5,EvadResz=14, Cim="The Sin-Eater",Rendezo="Mary Lambert",Premier="February 22, 2017",NezoSzam=1.54},
                new Epizod(){Sorszam=107,Evad=5,EvadResz=15, Cim="Fighting Fire with Fire",Rendezo="Michael Schultz",Premier="March 1, 2017",NezoSzam=1.60},
                new Epizod(){Sorszam=108,Evad=5,EvadResz=16, Cim="Checkmate",Rendezo="Ken Shane",Premier="March 15, 2017",NezoSzam=1.53},
                new Epizod(){Sorszam=109,Evad=5,EvadResz=17, Cim="Kapiushon",Rendezo="Kevin Tancharoen",Premier="March 22, 2017",NezoSzam=1.38},
                new Epizod(){Sorszam=110,Evad=5,EvadResz=18, Cim="Disbanded",Rendezo="JJ Makaro",Premier="March 29, 2017",NezoSzam=1.55},
                new Epizod(){Sorszam=111,Evad=5,EvadResz=19, Cim="Dangerous Liaisons",Rendezo="Joel Novoa",Premier="April 26, 2017",NezoSzam=1.36},
                new Epizod(){Sorszam=112,Evad=5,EvadResz=20, Cim="Underneath",Rendezo="Wendey Stanzler",Premier="May 3, 2017",NezoSzam=1.36},
                new Epizod(){Sorszam=113,Evad=5,EvadResz=21, Cim="Honor Thy Fathers",Rendezo="Laura Belsey",Premier="May 10, 2017",NezoSzam=1.65},
                new Epizod(){Sorszam=114,Evad=5,EvadResz=22, Cim="Missing",Rendezo="Mairzee Almas",Premier="May 17, 2017",NezoSzam=1.44},
                new Epizod(){Sorszam=115,Evad=5,EvadResz=23, Cim="Lian Yu",Rendezo="Jesse Warn",Premier="May 24, 2017",NezoSzam=1.72},
                new Epizod(){Sorszam=116,Evad=6,EvadResz=1, Cim="Fallout",Rendezo="James Bamford",Premier="October 12, 2017",NezoSzam=1.52},
                new Epizod(){Sorszam=117,Evad=6,EvadResz=2, Cim="Tribute",Rendezo="Laura Belsey",Premier="October 19, 2017",NezoSzam=1.51},
                new Epizod(){Sorszam=118,Evad=6,EvadResz=3, Cim="Next of Kin",Rendezo="Kevin Tancharoen",Premier="October 26, 2017",NezoSzam=1.34},
                new Epizod(){Sorszam=119,Evad=6,EvadResz=4, Cim="Reversal",Rendezo="Gregory Smith",Premier="November 2, 2017",NezoSzam=1.33},
                new Epizod(){Sorszam=120,Evad=6,EvadResz=5, Cim="Deathstroke Returns",Rendezo="Joel Novoa",Premier="November 9, 2017",NezoSzam=1.29},
                new Epizod(){Sorszam=121,Evad=6,EvadResz=6, Cim="Promises Kept",Rendezo="Antonio Negret",Premier="November 16, 2017",NezoSzam=1.28},
                new Epizod(){Sorszam=122,Evad=6,EvadResz=7, Cim="Thanksgiving",Rendezo="Gordon Verheul",Premier="November 23, 2017",NezoSzam=1.09},
                new Epizod(){Sorszam=123,Evad=6,EvadResz=8, Cim="Crisis on Earth-X, Part 2",Rendezo="James Bamford",Premier="November 27, 2017",NezoSzam=2.52},
                new Epizod(){Sorszam=124,Evad=6,EvadResz=9, Cim="Irreconcilable Differences",Rendezo="Laura Belsey",Premier="December 7, 2017",NezoSzam=1.30},
                new Epizod(){Sorszam=125,Evad=6,EvadResz=10, Cim="Divided",Rendezo="James Bamford",Premier="January 18, 2018",NezoSzam=1.38},
                new Epizod(){Sorszam=126,Evad=6,EvadResz=11, Cim="We Fall",Rendezo="Wendey Stanzler",Premier="January 25, 2018",NezoSzam=1.38},
                new Epizod(){Sorszam=127,Evad=6,EvadResz=12, Cim="All for Nothing",Rendezo="Mairzee Almas",Premier="February 1, 2018",NezoSzam=1.24},
                new Epizod(){Sorszam=128,Evad=6,EvadResz=13, Cim="The Devil's Greatest Trick",Rendezo="JJ Makaro",Premier="February 8, 2018",NezoSzam=1.30},
                new Epizod(){Sorszam=129,Evad=6,EvadResz=14, Cim="Collision Course",Rendezo="Ken Shane",Premier="March 1, 2018",NezoSzam=1.11},
                new Epizod(){Sorszam=130,Evad=6,EvadResz=15, Cim="Doppelganger",Rendezo="Kristin Windell",Premier="March 8, 2018",NezoSzam=1.28},
                new Epizod(){Sorszam=131,Evad=6,EvadResz=16, Cim="The Thanatos Guild",Rendezo="Joel Novoa",Premier="March 29, 2018",NezoSzam=1.12},
                new Epizod(){Sorszam=132,Evad=6,EvadResz=17, Cim="Brothers in Arms",Rendezo="Mark Bunting",Premier="April 5, 2018",NezoSzam=0.87},
                new Epizod(){Sorszam=133,Evad=6,EvadResz=18, Cim="Fundamentals",Rendezo="Ben Bray",Premier="April 12, 2018",NezoSzam=1.06},
                new Epizod(){Sorszam=134,Evad=6,EvadResz=19, Cim="The Dragon",Rendezo="Gordon Verheul",Premier="April 19, 2018",NezoSzam=0.96},
                new Epizod(){Sorszam=135,Evad=6,EvadResz=20, Cim="Shifting Allegiances",Rendezo="Alexandra La Roche",Premier="April 26, 2018",NezoSzam=0.87},
                new Epizod(){Sorszam=136,Evad=6,EvadResz=21, Cim="Docket No. 11-19-41-73",Rendezo="Andi Armaganian",Premier="May 3, 2018",NezoSzam=1.10},
                new Epizod(){Sorszam=137,Evad=6,EvadResz=22, Cim="The Ties That Bind",Rendezo="Tara Miele",Premier="May 10, 2018",NezoSzam=1.00},
                new Epizod(){Sorszam=138,Evad=6,EvadResz=23, Cim="Life Sentence",Rendezo="James Bamford",Premier="May 17, 2018",NezoSzam=1.35},
                new Epizod(){Sorszam=139,Evad=7,EvadResz=1, Cim="Inmate 4587",Rendezo="James Bamford",Premier="October 15, 2018",NezoSzam=1.43},
                new Epizod(){Sorszam=140,Evad=7,EvadResz=2, Cim="The Longbow Hunters",Rendezo="Laura Belsey",Premier="October 22, 2018",NezoSzam=1.18},
                new Epizod(){Sorszam=141,Evad=7,EvadResz=3, Cim="Crossing Lines",Rendezo="Gordon Verheul",Premier="October 29, 2018",NezoSzam=1.15},
                new Epizod(){Sorszam=142,Evad=7,EvadResz=4, Cim="Level Two",Rendezo="Ben Bray",Premier="November 5, 2018",NezoSzam=1.08},
                new Epizod(){Sorszam=143,Evad=7,EvadResz=5, Cim="The Demon",Rendezo="Mark Bunting",Premier="November 12, 2018",NezoSzam=1.26},
                new Epizod(){Sorszam=144,Evad=7,EvadResz=6, Cim="Due Process",Rendezo="Kristin Windell",Premier="November 19, 2018",NezoSzam=1.03},
                new Epizod(){Sorszam=145,Evad=7,EvadResz=7, Cim="The Slabside Redemption",Rendezo="James Bamford",Premier="November 26, 2018",NezoSzam=1.31},
                new Epizod(){Sorszam=146,Evad=7,EvadResz=8, Cim="Unmasked",Rendezo="Alexandra La Roche",Premier="December 3, 2018",NezoSzam=1.35},
                new Epizod(){Sorszam=147,Evad=7,EvadResz=9, Cim="Elseworlds, Part 2",Rendezo="James Bamford",Premier="December 10, 2018",NezoSzam=2.06},
                new Epizod(){Sorszam=148,Evad=7,EvadResz=10, Cim="My Name Is Emiko Queen",Rendezo="Andi Armaganian",Premier="January 21, 2019",NezoSzam=1.22},
                new Epizod(){Sorszam=149,Evad=7,EvadResz=11, Cim="Past Sins",Rendezo="David Ramsey",Premier="January 28, 2019",NezoSzam=1.18},
                new Epizod(){Sorszam=150,Evad=7,EvadResz=12, Cim="Emerald Archer",Rendezo="Glen Winter",Premier="February 4, 2019",NezoSzam=1.07},
                new Epizod(){Sorszam=151,Evad=7,EvadResz=13, Cim="Star City Slayer",Rendezo="Gregory Smith",Premier="February 11, 2019",NezoSzam=1.09},
                new Epizod(){Sorszam=152,Evad=7,EvadResz=14, Cim="Brothers & Sisters",Rendezo="Marcus Stokes",Premier="March 4, 2019",NezoSzam=0.89},
                new Epizod(){Sorszam=153,Evad=7,EvadResz=15, Cim="Training Day",Rendezo="Ruba Nadda",Premier="March 11, 2019",NezoSzam=1.02},
                new Epizod(){Sorszam=154,Evad=7,EvadResz=16, Cim="Star City 2040",Rendezo="James Bamford",Premier="March 18, 2019",NezoSzam=1.00},
                new Epizod(){Sorszam=155,Evad=7,EvadResz=17, Cim="Inheritance",Rendezo="Patia Prouty",Premier="March 25, 2019",NezoSzam=1.01},
                new Epizod(){Sorszam=156,Evad=7,EvadResz=18, Cim="Lost Canary",Rendezo="Kristin Windell",Premier="April 15, 2019",NezoSzam=0.71},
                new Epizod(){Sorszam=157,Evad=7,EvadResz=19, Cim="Spartan",Rendezo="Avi Youabian",Premier="April 22, 2019",NezoSzam=0.71},
                new Epizod(){Sorszam=158,Evad=7,EvadResz=20, Cim="Confessions",Rendezo="Tara Miele",Premier="April 29, 2019",NezoSzam=0.64},
                new Epizod(){Sorszam=159,Evad=7,EvadResz=21, Cim="Living Proof",Rendezo="Gordon Verheul",Premier="May 6, 2019",NezoSzam=0.63},
                new Epizod(){Sorszam=160,Evad=7,EvadResz=22, Cim="You Have Saved This City",Rendezo="James Bamford",Premier="May 13, 2019",NezoSzam=0.95},

            };
        }
    }
}
